# Generated by Django 5.1.7 on 2025-03-19 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('role', models.CharField(choices=[('bat', 'Batsman'), ('bow', 'Bowler'), ('all', 'All Rounder'), ('wk', 'Wicket Keeper')], max_length=100)),
                ('country', models.CharField(choices=[('india', 'India'), ('aus', 'Australia'), ('eng', 'England'), ('sa', 'South Africa'), ('ban', 'Bangladesh')], max_length=100)),
                ('profile_pic', models.ImageField(upload_to='player/')),
                ('is_captain', models.BooleanField()),
                ('fav_food', models.CharField(max_length=100)),
            ],
        ),
    ]
