# Generated by Django 5.1.7 on 2025-03-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
    ]
