# Generated by Django 5.1.7 on 2025-03-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_player_is_captain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('Australia', 'Australia'), ('England', 'England'), ('South Africa', 'South Africa'), ('Bangladesh', 'Bangladesh')], max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('Batsman', 'Batsman'), ('Bowler', 'Bowler'), ('All Rounder', 'All Rounder'), ('Wicket Keeper', 'Wicket Keeper')], max_length=100),
        ),
    ]
