# Generated by Django 5.1.7 on 2025-03-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_player_country_alter_player_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='fav_food',
        ),
        migrations.AddField(
            model_name='player',
            name='fav_food',
            field=models.ManyToManyField(to='crud.food'),
        ),
    ]
