# Generated by Django 5.1.7 on 2025-03-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_food_remove_player_fav_food_player_fav_food'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='country',
            field=models.CharField(choices=[('India', 'India'), ('Australia', 'Australia'), ('England', 'England'), ('South Africa', 'South Africa'), ('Bangladesh', 'Bangladesh'), ('Sri Lanka', 'Sri Lanka'), ('NewZeland', 'NewZeland'), ('WestIndies', 'WestIndies'), ('Other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_captain',
            field=models.BooleanField(),
        ),
    ]
