# Generated by Django 5.1.7 on 2025-03-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_player_country_alter_player_is_captain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='is_captain',
            field=models.BooleanField(default=False),
        ),
    ]
